### PR TITLE
Change the Content-Type in the response header

### PR DESCRIPTION
**Pull request by Gradlon**
Hey I use Fastify and in my Scenario the Content-Type was plain text, with this small change we can make sure that the content type is set correctly.

### CODE REVIEW

**Review by shekohex — APPROVED** [review]
LGTM!

**Comment by shekohex** [comment]
Thank you

**Comment by Gradlon** [comment]
You are welcome.
Can you publish the package to npm?

**Comment by shekohex** [comment]
Sure, will do shortly. Sorry for the delay.

**Comment by shekohex** [comment]
Done in `nestjs-flub@0.1.2`

**Pull request merged**
